# Site settings
title: Teyrow
email: andreas.josephson@teyrow.se
description: > # this means to ignore newlines until "baseurl:"
  Enligt principen 'Max 10 css-regler' avhandlas tankar om livet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.teyrow.com" # the base hostname & protocol for your site
lang: "sv-SE"
twitter_username:
github_username:  teyrow

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"
kramdown:
  smart_quotes:   rsquo,rsquo,rdquo,rdquo


